import type { Metadata } from "next";
import { Roboto, Jost } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import SmoothScroll from "@/components/SmoothScroll";
import Providers from "@/components/Providers";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bending Waters",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${roboto.variable} ${jost.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <Providers>
          {children}
          <SmoothScroll />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
